hparams = [
    {
        "model": "CatBoost",
        "dataset": "mimic-iv",
        "task": "outcome",
        "max_depth": 5,
        "n_estimators": 50,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "XGBoost",
        "dataset": "mimic-iv",
        "task": "outcome",
        "max_depth": 5,
        "n_estimators": 50,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        'model': 'GRU',
        'dataset': 'mimic-iv',
        'task': 'outcome',
        'epochs': 50,
        'patience': 10,
        'batch_size': 1024,
        'learning_rate': 0.001,
        'main_metric': 'auprc',
        'demo_dim': 2,
        'lab_dim': 59,
        'hidden_dim': 128,
        'output_dim': 1
    },
    {
        'model': 'AdaCare',
        'dataset': 'mimic-iv',
        'task': 'outcome',
        'epochs': 50,
        'patience': 10,
        'batch_size': 1024,
        'learning_rate': 0.001,
        'main_metric': 'auprc',
        'demo_dim': 2,
        'lab_dim': 59,
        'hidden_dim': 128,
        'output_dim': 1
    },
    {
        "model": "CatBoost",
        "dataset": "tjh",
        "task": "outcome",
        "max_depth": 5,
        "n_estimators": 50,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "XGBoost",
        "dataset": "tjh",
        "task": "outcome",
        "max_depth": 5,
        "n_estimators": 50,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        'model': 'GRU',
        'dataset': 'tjh',
        'task': 'outcome',
        'epochs': 50,
        'patience': 10,
        'batch_size': 1024,
        'learning_rate': 0.001,
        'main_metric': 'auprc',
        'demo_dim': 2,
        'lab_dim': 73,
        'hidden_dim': 128,
        'output_dim': 1
    },
    {
        'model': 'AdaCare',
        'dataset': 'tjh',
        'task': 'outcome',
        'epochs': 50,
        'patience': 10,
        'batch_size': 1024,
        'learning_rate': 0.001,
        'main_metric': 'auprc',
        'demo_dim': 2,
        'lab_dim': 73,
        'hidden_dim': 128,
        'output_dim': 1
    },
    {
        "model": "GBDT",
        "dataset": "mimic-iv",
        "task": "outcome",
        "max_depth": 5,
        "n_estimators": 100,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "GBDT",
        "dataset": "tjh",
        "task": "outcome",
        "max_depth": 5,
        "n_estimators": 100,
        "learning_rate": 0.1,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "RF",
        "dataset": "mimic-iv",
        "task": "outcome",
        "max_depth": 15,
        "n_estimators": 100,
        "learning_rate": 1.0,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "RF",
        "dataset": "tjh",
        "task": "outcome",
        "max_depth": 15,
        "n_estimators": 100,
        "learning_rate": 1.0,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        'model': 'StageNet',
        'dataset': 'mimic-iv',
        'task': 'outcome',
        'epochs': 50,
        'patience': 10,
        'batch_size': 1024,
        'learning_rate': 0.001,
        'main_metric': 'auprc',
        'demo_dim': 2,
        'lab_dim': 59,
        'hidden_dim': 128,
        'output_dim': 1
    },
    {
        'model': 'StageNet',
        'dataset': 'tjh',
        'task': 'outcome',
        'epochs': 50,
        'patience': 10,
        'batch_size': 1024,
        'learning_rate': 0.001,
        'main_metric': 'auprc',
        'demo_dim': 2,
        'lab_dim': 73,
        'hidden_dim': 128,
        'output_dim': 1
    },
    {
        'model': 'TCN',
        'dataset': 'mimic-iv',
        'task': 'outcome',
        'epochs': 50,
        'patience': 10,
        'batch_size': 1024,
        'learning_rate': 0.001,
        'main_metric': 'auprc',
        'demo_dim': 2,
        'lab_dim': 59,
        'hidden_dim': 128,
        'output_dim': 1
    },
    {
        'model': 'TCN',
        'dataset': 'tjh',
        'task': 'outcome',
        'epochs': 50,
        'patience': 10,
        'batch_size': 1024,
        'learning_rate': 0.001,
        'main_metric': 'auprc',
        'demo_dim': 2,
        'lab_dim': 73,
        'hidden_dim': 128,
        'output_dim': 1
    },
    {
        'model': 'AICare',
        'dataset': 'mimic-iv',
        'task': 'outcome',
        'epochs': 50,
        'patience': 10,
        'batch_size': 1024,
        'learning_rate': 0.001,
        'main_metric': 'auprc',
        'demo_dim': 2,
        'lab_dim': 59,
        'hidden_dim': 128,
        'output_dim': 1
    },
    {
        'model': 'AICare',
        'dataset': 'tjh',
        'task': 'outcome',
        'epochs': 50,
        'patience': 10,
        'batch_size': 1024,
        'learning_rate': 0.001,
        'main_metric': 'auprc',
        'demo_dim': 2,
        'lab_dim': 73,
        'hidden_dim': 128,
        'output_dim': 1
    },
    {
        'model': 'RETAIN',
        'dataset': 'mimic-iv',
        'task': 'outcome',
        'epochs': 50,
        'patience': 10,
        'batch_size': 1024,
        'learning_rate': 0.001,
        'main_metric': 'auprc',
        'demo_dim': 2,
        'lab_dim': 59,
        'hidden_dim': 128,
        'output_dim': 1
    },
    {
        'model': 'RETAIN',
        'dataset': 'tjh',
        'task': 'outcome',
        'epochs': 50,
        'patience': 10,
        'batch_size': 1024,
        'learning_rate': 0.001,
        'main_metric': 'auprc',
        'demo_dim': 2,
        'lab_dim': 73,
        'hidden_dim': 128,
        'output_dim': 1
    },
    {
        "model": "DT",
        "dataset": "mimic-iv",
        "task": "outcome",
        "max_depth": 5,
        "n_estimators": 10,
        "learning_rate": 0.01,
        "batch_size": 81920,
        "main_metric": "auprc",
    },
    {
        "model": "DT",
        "dataset": "tjh",
        "task": "outcome",
        "max_depth": 5,
        "n_estimators": 10,
        "learning_rate": 0.01,
        "batch_size": 81920,
        "main_metric": "auprc",
    },

]